# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b5a213b6f4697e3bf40e5d955bdb47499503e7b3693aabb2f1867e0dac56c0fb8f49076f758f6566f5bce0437d5b450139f4dca69697acc83c0e61296df4a6

test:
  secret_key_base: 16830f82d84266730283165231933e6e2917e8877ab70d9d7fad47064676d000b1d6ea0eaa35835299d220e89b267807b5f3b4defa8fef0967c2a2d3aa16386a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
